=head1 Build Perl

This is a very informal bag of stuff that might possibly perhaps who knows help
you build your own perl binary.  The Why Would I Want To Do That is at
L<http://larig.github.com/build-perl/>.  At present the package is bhe bare
bones we need right now, with the intention to make it more generally useful
later.

Larig Tech

24 October 2012

=cut
